version: "3"

tasks:
  grpc-generate-and-push:
    aliases:
      - full-gen
    desc: "Generate code from proto files and push them on github"
    cmds:
      - protoc -I proto proto/{{.PROTO}}/*.proto --go_out=gen/go --go_opt=paths=source_relative --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative
      - git add .
      - git commit -m '{{.MSG}}'
      - git tag -a '{{.TAG}}' -m '{{.MSG}}'
      - git push -u origin {{.BR}}
      - git push origin --tags
  
  generate-tag:
    aliases:
      - tag
    desc: "Create tag on github"
    cmds:
      - git tag -a '{{.TAG}}' -m '{{.MSG}}'
      - git push -u origin '{{.BR}}'
      - git push origin --tags